[tool.mypy]
ignore_missing_imports = true
python_version = "3.11"
strict = false
files = ["src/meritscalc"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
per-file-ignores = { "tests/*" = ["E712", "F841", "F821", "F401"] }
